name: Build Debian Package

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential devscripts debhelper dpkg

      - name: Set permissions
        run: |
          chmod +x usr/bin/projetor-enc
          chmod +x usr/local/bin/projetor-enc-wrapper
          chmod +x usr/sbin/epson-projector-cmd
          chmod +x debian/postinst
          chmod +x debian/prerm

      - name: Build .deb package
        run: |
          mkdir -p build/DEBIAN
          mkdir -p build/usr/bin
          mkdir -p build/usr/local/bin
          mkdir -p build/usr/sbin
          mkdir -p build/etc/systemd/system

          # Copia os arquivos
          cp -r usr/bin/projetor-enc build/usr/bin/
          cp -r usr/local/bin/projetor-enc-wrapper build/usr/local/bin/
          cp -r usr/sbin/epson-projector-cmd build/usr/sbin/
          cp -r etc/systemd/system/projetor-enc.service build/etc/systemd/system/

          # Copia os arquivos de controle
          cp debian/control build/DEBIAN/
          cp debian/postinst build/DEBIAN/
          cp debian/prerm build/DEBIAN/

          # Garante permissões corretas
          chmod 755 build/usr/bin/projetor-enc
          chmod 755 build/usr/local/bin/projetor-enc-wrapper
          chmod 755 build/usr/sbin/epson-projector-cmd
          chmod 644 build/etc/systemd/system/projetor-enc.service
          chmod 755 build/DEBIAN/postinst
          chmod 755 build/DEBIAN/prerm

          # Constrói o pacote
          dpkg-deb --build build projetor-enc.deb

      - name: Upload .deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: projetor-enc
          path: projetor-enc.deb
