name: Upload test

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create dummy file
        run: echo "test" > projetor-enc.deb

      - name: Upload file to Release
        uses: softprops/action-gh-release@v2
        with:
          files: projetor-enc.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
